/**
 * build.mjs —— 更新包的编译脚本（自 monorepo 迁出，转译口径不变）。
 *
 * 只转译不打包：用本包 devDependencies 里的 esbuild 把 src/ 下每个 TS 文件
 * 一对一转成 dist/ 下的同名 JS；另跑 tsc --noEmit 只做类型检查。
 * 生成的 JS 不提交到 git（发布前跑 build 本地生成）；改了 TS 没重新生成，测试直接引用 dist 会过期，由单测兜住。
 *
 * 用法：node build.mjs（在仓根跑；package.json 的 npm run build 就是它）
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { spawnSync } from 'node:child_process'
import { createRequire } from 'node:module'
import * as esbuild from 'esbuild'

// 本仓即本包：build.mjs 住在包根，src/ 与 dist/ 都是它的直接子目录。
const PKG_DIR = dirname(fileURLToPath(import.meta.url))
const SRC_DIR = resolve(PKG_DIR, 'src')
const OUT_DIR = resolve(PKG_DIR, 'dist')

const UNITS = [
  { ts: 'config.ts', js: 'config.js' },
  { ts: 'ports.ts', js: 'ports.js' },
  { ts: 'service.ts', js: 'service.js' },
  { ts: 'redaction.ts', js: 'redaction.js' },
  { ts: 'diag.ts', js: 'diag.js' },
  { ts: 'changelog.ts', js: 'changelog.js' },
  { ts: 'changelog-io.ts', js: 'changelog-io.js' },
  { ts: 'commands.ts', js: 'commands.js' },
  { ts: 'store.ts', js: 'store.js' },
  { ts: 'reader.ts', js: 'reader.js' },
  { ts: 'gate.ts', js: 'gate.js' },
  { ts: 'queue.ts', js: 'queue.js' },
  { ts: 'batch.ts', js: 'batch.js' },
  { ts: 'batch-run.ts', js: 'batch-run.js' },
  { ts: 'host-batch.ts', js: 'host-batch.js' },
  { ts: 'panel-batch.ts', js: 'panel-batch.js' },
  { ts: 'entry.ts', js: 'entry.js' },
  { ts: 'host.ts', js: 'host.js' },
  { ts: 'client.ts', js: 'client.js' },
  { ts: 'panel.ts', js: 'panel.js' },
]

function headerFor(tsName) {
  return `// AUTO-GENERATED by node build.mjs — DO NOT EDIT. Source: src/${tsName}\n`
}

/** 与门禁同一口径：转译加包头，换行归一，末尾恰好一个换行。 */
export function transpileUnit(tsName) {
  const tsPath = resolve(SRC_DIR, tsName)
  const source = readFileSync(tsPath, 'utf8')
  const out = esbuild.transformSync(source, {
    loader: 'ts',
    format: 'esm',
    // 保守目标：Node 宿主与浏览器闭包两边都跑得动。
    target: 'es2020'
  })
  const body = out.code.replace(/\r\n/g, '\n').replace(/\s+$/, '') + '\n'
  return headerFor(tsName) + body
}

function runTypeCheck() {
  const require = createRequire(resolve(PKG_DIR, 'package.json'))
  let tscBin
  try {
    tscBin = resolve(dirname(require.resolve('typescript/package.json')), 'bin/tsc')
  } catch {
    throw new Error('[dsh-plugin-update] 找不到 typescript：请先运行 npm install（本包 devDependencies 含 typescript）')
  }
  const r = spawnSync(process.execPath, [tscBin, '-p', resolve(PKG_DIR, 'tsconfig.json')], {
    encoding: 'utf8'
  })
  if (r.status !== 0) {
    throw new Error(`[dsh-plugin-update] tsc --noEmit 未通过：\n${r.stdout || ''}${r.stderr || ''}`)
  }
  console.log('[dsh-plugin-update] tsc --noEmit 通过')
}

// 类型定义随包分发（#17：公开入口一律带完整类型定义，不做源码级复用）。
// tsconfig 是 noEmit 只检查，这里另起一次显式调用只产 .d.ts（运行时 JS 不动）。
function runDeclarationEmit() {
  const require = createRequire(resolve(PKG_DIR, 'package.json'))
  let tscBin
  try {
    tscBin = resolve(dirname(require.resolve('typescript/package.json')), 'bin/tsc')
  } catch {
    throw new Error('[dsh-plugin-update] 找不到 typescript：请先运行 npm install（本包 devDependencies 含 typescript）')
  }
  const { readdirSync } = require('node:fs')
  const inputs = readdirSync(SRC_DIR).filter((n) => n.endsWith('.ts')).map((n) => resolve(SRC_DIR, n))
  const r = spawnSync(process.execPath, [tscBin,
    '--target', 'ES2020',
    '--lib', 'ES2020',
    '--module', 'ESNext',
    '--moduleResolution', 'Bundler',
    '--strict', '--skipLibCheck',
    '--declaration', '--emitDeclarationOnly',
    '--outDir', OUT_DIR,
  ].concat(inputs), { encoding: 'utf8' })
  if (r.status !== 0) {
    throw new Error(`[dsh-plugin-update] tsc 声明产出未通过：\n${r.stdout || ''}${r.stderr || ''}`)
  }
  console.log('[dsh-plugin-update] .d.ts 声明已产出 dist/')
}

function main() {
  runTypeCheck()
  mkdirSync(OUT_DIR, { recursive: true })
  for (const u of UNITS) {
    const text = transpileUnit(u.ts)
    const outPath = resolve(OUT_DIR, u.js)
    writeFileSync(outPath, text, 'utf8')
    console.log(`[dsh-plugin-update] ${u.ts} -> dist/${u.js}（${text.split('\n').length} 行）`)
  }
  runDeclarationEmit()
}

const invoked = process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)
if (invoked) {
  try {
    main()
  } catch (e) {
    console.error((e && e.message) || e)
    process.exit(1)
  }
}
